### ISSUE TITLE
Fieldsets werden ohne erfüllte Bedingung angezeigt

### ISSUE THREAD

**Issue by TheRedTiger** [terminal42/contao-conditionalformfields#12]
Hallo,

wenn ein Benutzer beim ausfüllen des Formulars ein Pflichtfeld vergisst und auf senden klickt, wird dies wie gewünscht von Contao bemängelt. Weiterhin werden jedoch alle Fieldsets, welche mit ConditionalFormFields ausgeblendet wurden, wieder eingeblendet.

Woran könnte dies liegen?

Grüße
Jörg

**Comment by aschempp** [comment]
Dann scheint es auf deiner Seite einen Javascript-Fehler zu geben, du müsstest mal die Browser-Konsole prüfen.

**Comment by TheRedTiger** [comment]
Der Fehler hat sich in Luft aufgelöst. 8-)
