### ISSUE TITLE
not working while form is included via insert-tag

### ISSUE THREAD

**Issue by basistom** [terminal42/contao-conditionalformfields#13]
The extension is not working if the form is included via insert-tag {{insert_form::*}}.
I think the issue comes from the hook outputFrontendTemplate 

> which is applied before the replacement of insert tags

[https://docs.contao.org/books/api/extensions/hooks/outputFrontendTemplate.html]

**Comment by qzminski** [comment]
Fixed in c3c9a74.

**Comment by qzminski** [comment]
@basistom can you try that fix and see if it's working correctly now?

**Comment by basistom** [comment]
Works!
