### ISSUE TITLE
in_array und Einzelabfragen funktionieren nicht

### ISSUE THREAD

**Issue by TheRedTiger** [terminal42/contao-conditionalformfields#14]
Hallo Zusammen,

ich habe ein Checkbox-Menü (sparte) mit 3 Checkboxen (leben, kranken, sach).

Wenn ich das zugehörige Fieldset für leben einblenden möchte tut sich einfach nix.
Als Bedingungen habe ich folgendes eingegeben:

`in_array('leben', $sparte)` - Stimmt doch so, oder?

Wenn ich die Checkboxen auf nur eine einzige z.B. leben reduziere und die Bedingung wie folgt anpasse, funktioniert es.

`$sparte == 'leben'`

Laut Beschreibung sagt Ihr, die Bedingung für eine Checkbox lautet: `$sparte == '1'`
Aber dies funktioniert ebenso nicht wie das in_array.

Was kann ich tun, damit es läuft???

Ich verwende **Contao 3.5.19 und Conditionalformfields 2.1.5**

Vielen Dank im Voraus.

Beste Grüße
Jörg

**Comment by Toflar** [comment]
Fixed. Bitte testen, wenn das Feedback positiv ist, veröffentliche ich die 2.1.6 :-)

**Comment by TheRedTiger** [comment]
Servus,
Test **BESTANDEN**. Es funktioniert wieder wie gewohnt.
Danke.

**Comment by Toflar** [comment]
Ok, danke für's Testen. Version veröffentlicht und kann somit über Composer gezogen werden.
