### ISSUE TITLE
Methode im validateFormField-Hook entfernt immer alle vorherigen Field-Error

### ISSUE THREAD

**Issue by bildschirmartist** [terminal42/contao-conditionalformfields#15]
Der Fehler liegt in der Klasse `ConditionalFormFields`:
Grund hierfür ist die Validierung innerhalb der Fieldsets: Hier gibt die Anonymous function innerhalb des `condition`-Felds immer `false` zurück, da beim Aufbau des `$fieldsets` für die `condition` kein Funktions-Parameter mitgegeben wird (s. `registerFieldsetes`-Methode)

Falsch (Zeile 56-61):
```
static::$fieldsets[$formId][$fieldset] = array(
    'condition' => function () use ($condition) {
        return eval($condition);
    },
    'fields' => array(),
);
```

Korrekt:
```
static::$fieldsets[$formId][$fieldset] = array(
    'condition' => function ($arrPost) use ($condition) {
        return eval($condition);
    },
    'fields' => array(),
);
```

**Comment by Toflar** [comment]
Ich verstehe das Problem leider nicht. Das was du bei "Falsch" geschrieben hast, entspricht nicht dem aktuellen Stand der Code-Base. Magst du vielleicht einfach direkt einen Pull Request machen, dann sieht man den Code-Change? :)

**Comment by bildschirmartist** [comment]
Hallo Toflar,
habe einen Merge Request erstellt. In meinem obigen Post hatte ich "Korrekt" und "Falsch" leider vertauscht ^^

**Comment by Toflar** [comment]
Closed in favor of https://github.com/terminal42/contao-conditionalformfields/pull/16
