### ISSUE TITLE
Sessiondaten werden nicht gelöscht

### ISSUE THREAD

**Issue by Schmidty2** [terminal42/contao-conditionalformfields#17]
Conditionalformfileds löscht beim erneuten Aufruf und Versand eines Formulars die Sessiondaten der ausgeblendeten Felder nicht.

Beispiel:
Ein Formular mit Conditinalformfileds - je nach Auswahl Erwachsener oder Kind werden unterschiedliche Formularfelder eingeblendet. Das funktioniert auch alles.
Wenn jetzt eine Person Erwachsener wählt, das Formular ausfüllt und versendet und anschließend die nächste Person am gleichen PC das Formular aufruft (ohne den Browser zu beenden) und Kind wählt, werden bei der Formularübermittlung die Daten des Erwachsenen der das Formular vorher ausgefüllt hat ebenfalls mit übermittelt.
Wird erneut Erwachsener gewählt, werden die bisherigen Daten überschrieben.

**Comment by Toflar** [comment]
Conditionalformfields nutzt überhaupt keine Session...welche Version nutzt du?

**Comment by aschempp** [comment]
Ich vermute mal das bezieht sich auf mp-forms oder efg?

**Comment by Schmidty2** [comment]
Hallo,
nein es ist nicht mp-forms und der EFG ist auch nicht installiert.
Ich kann das Ganze mit mehreren Browsern nachvollziehen (Firefox, IE, Chrome, Safari, Safari for iPad).

Ich habe eine Testseite - kann ich die Adresse der Seite irgendwie per PN oder E-Mail an Euch schicken?

Danke für Eure Unterstützung.

**Comment by Schmidty2** [comment]
Hallo,
hier der [Link](http://bit.ly/2kHt9QD)
Auf der Formularantwortseite sieht man die Felder und das Problem:
![Formularantwortseite](https://cloud.githubusercontent.com/assets/2067428/22741458/98d73f8e-ee13-11e6-8205-8feabbd8862f.png)

Danke, dass ihr Euch das Ganze anschaut.

**Comment by Schmidty2** [comment]
Hallo,
ich habe das Ganze jetzt einmal genauer ausgetestet.
Tatsache ist, dass alle von Conditionalformfields ausgeblendeten Formularfelder beim erneuten Aufruf des Formulars nicht gelöscht werden. Und die Inhalte dieser ausgeblendeten Felder werden beim Versenden des Formulars erneut übertragen, wenn beim zweiten versenden eine andere Option ausgewählt und damit andere Formularfelder eingeblendet und ausgefüllt werden.

Abhilfe habe ich jetzt (vorerst) dadurch geschaffen, dass ich beim Aufruf des Formulars den value der entsprechenden Felder überschreibe. Dazu verwende ich im Formulargenerator im entsprechenden Formular am Anfang ein Element Eigener HTML-Code, das ich per CSS ausblende:

![grafik](https://cloud.githubusercontent.com/assets/2067428/23105246/4864dd46-f6dc-11e6-93f7-c7ffe430df7a.png)

Gibt es dafür eine bessere (elegantere) Lösung mit PHP oder JS?

**Comment by Schmidty2** [comment]
Sorry,
wollte den Beitrag ergänzen und nicht komplett schließen.

**Comment by fritzmg** [comment]
Das Problem kann ich bestätigen. Wenn man das Formular einmal absendet, danach wieder auf das Formular geht und mit anderen Daten (wodurch ein anderes Fieldset eingeblendet wird) erneut absendet, werden die Daten die beim ersten mal absenden aktiv waren - aber beim zweiten mal ausgeblendet sind, auch mit geschickt.

**Comment by fritzmg** [comment]
> Conditionalformfields nutzt überhaupt keine Session...welche Version nutzt du?

Die Extension nicht - Contao speichert die Feldwerte aber tatsächlich in der Session. Siehe https://github.com/contao/core/blob/3.5.27/system/modules/core/forms/Form.php#L509

Und in der Input Klasse wird das bei einem `FORM_SUBMIT` ausgelesen - über diesen Weg kommt der Wert wieder ins Widget: https://github.com/contao/core/blob/3.5.27/system/modules/core/library/Contao/Input.php#L786-L789

Das ist bei normalen Formularen kein Problem, weil da der Wert sowieso wieder mit dem Wert überschrieben wird, den der User submitted hat. Bei Conditionalformfields ist es aber ein Problem, da der Benutzer bei versteckten Formularfeldern keinen neuen Wert mehr submitted - aber in der Session noch Werte vorhanden sein können.

**Comment by fritzmg** [comment]
Hat jemand eine Ahnung, warum das überhaupt in der Session gespeichert wird?

**Comment by fritzmg** [comment]
I have created a PR in the contao/core: https://github.com/contao/core/pull/8707

If this PR is rejected and/or nothing is changed on the Contao side in general, this fix could also be implemented in `processFormData` hook within the terminal42/contao-conditionalformfields extension. I will make a PR for that as well if necessary.

**Comment by fritzmg** [comment]
Should be a simple fix: #18

**Comment by aschempp** [comment]
Fixed in 24d768156c76b91efb602c901d5b419d3892107b
