### ISSUE TITLE
type hint for original classes not namespaced classes

### ISSUE THREAD

**Issue by backbone87** [terminal42/contao-conditionalformfields#19]
following error after update to php 7.0:

```
Fatal error: Uncaught exception TypeError with message Argument 4 passed to ConditionalFormFields::loadFormField() must be an instance of Form, instance of Hofff\Contao\FormTools\Frontend\Form given, called in system/modules/core/forms/Form.php on line 191 thrown in composer/vendor/terminal42/contao-conditionalformfields/ConditionalFormFields.php on line 95
```

-> `Hofff\Contao\FormTools\Frontend\Form extends Contao\Form`

the problem is, that type hinting for a class will not trigger an autoload (anymore?) and you hint for the alias, which is not loaded therefore. and contao does not automatically alias the original namespaced class, but only when you actually "use" it (static call or constructor call or reflection).

The error of PHP is correct, because there is no `Form` class and an autoload (to get the alias from contao class loader) will not happen, because its just a type hint.

solution: type hint for the original, not the alias

**Comment by aschempp** [comment]
This is a bug in your implementation. You must register your namespace so your class becomes the global alias.

**Comment by aschempp** [comment]
Alternatively, extend the global class name, not the namespaced one.

**Comment by backbone87** [comment]
Its not a bug in my impl. I dont want to overwrite the Core class. I want to extend it.

And i dont want to extend a Potential overwritten alias, but i want to extend the real Core class.

**Comment by aschempp** [comment]
I know, but that's how the Contao class loader works. If you want to override a core class, you have to register your namespace. https://docs.contao.org/books/cookbook/de/Autoloading.html

**Comment by backbone87** [comment]
Again, __i do not want to overwrite a core class__

**Comment by aschempp** [comment]
If you don't, then extend the global alias. So other can override the core class and your implementation will correctly inherit from them.

**Comment by backbone87** [comment]
Also where is a Problem when you change the type hint or just remove it?

**Comment by aschempp** [comment]
Changing the type hint would cause issue with people using the global namespace and not extending core, which is how it's designed to be. I agree it's sorta stupid, but that's just how Contao works. Where's the problem in just extending the global class? 😉

**Comment by backbone87** [comment]
1. removing the type hint __will__ work and should be the way to go. E.g. If you want to use MCW all load/save signatures have an MCWWidget as 2nd arg and not a DC. 

2. changing the type hint would work for everyone except for ppl trying to overwrite a core alias without extending the core class ( from namespace), which is double bad. You should never have to overwrite a core alias and if you do at least dont violate liskov.

Can we just stop argue about this one? I wouldnt request this change, if it wouldnt broaden compat.

**Comment by aschempp** [comment]
> removing the type hint will work and should be the way to go.

Great idea, let's remove type hints everywhere! Will you create a PR for symfony/symfony?

**Comment by backbone87** [comment]
... stop cherry picking. WTF is wrong with you? Are you unable to see, understand and/or admit, that your impl prevents writing clean forward compatible code? If that is the standard you take for your extensions fine, just say it and i ll leave it alone.
