### ISSUE TITLE
Support checkbox arrays

### ISSUE THREAD

**Issue by aschempp** [terminal42/contao-conditionalformfields#2]
It should be possible to apply `$field == 'value'` on checkbox arrays too. Currently that's not possible because the last checkbox will win in the values array.

Also, the name is retrieved, which would be `$field[]` but that makes no sense. So we need to strip away the `[]` at the end. But preserve any valid array keys if available (so the condition would be `$field[key] == 'something`.

**Comment by MichaelSFD** [comment]
Hallo,

ich hoffe, es ist okay, dass ich das alte Schätzchen wieder hervorhole.

Ich habe genau das Problem mit den Klammern bei einer Checkbox mit mehreren Einträgen. Das Feld hat den Namen update und Contao macht daraus uptade[]. Und schon greift die Regel nicht.

Könnt ihr mir die Lösung verraten?

Ich habe Contao 4.13.34 und PHP 8.1.

Vielen Dank und viele Grüße

Michael

**Comment by aschempp** [comment]
Mit Bedienungsfragen wendest du dich am besten an die Contao Community (https://to.contao.org/support), dann können dir alle mit entsprechenden Erfahrungen helfen 😊

**Comment by MichaelSFD** [comment]
Hi Andreas,

danke, ich dachte nur, weil ihr das Problem hier so ausführlich bearbeitet habt.

Ich bin so frei und nenne es mal "Problem", denn mit Bedienungsfragen hat das ja nicht wirklich was zu tun.

Gruß Michael
