### ISSUE TITLE
override JavaScript functions or provide events

### ISSUE THREAD

**Issue by fritzmg** [terminal42/contao-conditionalformfields#22]
In a project I needed to know whenever a fieldset is being shown or hidden (for instance to initialize an `Autogrow` script on an initially hidden `textarea`; or to fade-in/out the fieldset instead of show/hide). I ended up doing the following:
```JavaScript
(function($, undefined)
{
    'use strict';

    $(window).on('load', function()
    {
        /**
         * Override some ConditionalFormFields functions
         */
        $('form').each(function()
        {
            var conditionalFormFields = $(this).data('plugin_conditionalFormFields');

            if (conditionalFormFields === undefined)
            {
               return true;
            }

            Object.getPrototypeOf(conditionalFormFields).showFieldset = function(id)
            {
               // do custom code here
               // …
            };

            return false;
        });
    });

})(jQuery);
```
That isn't very pretty though. So I was wondering if there is a better way already or may be the JavaScript of conditionalformfields should be altered in a way, so things like this can be implemented more easily.

**Comment by Toflar** [comment]
What about adding events so you can register to them?

**Comment by fritzmg** [comment]
That would be great :). However with an event I still would not be able to override the default show/hide behaviour with something else (like fadeIn or fadeOut for example).

**Comment by Toflar** [comment]
Yeah well, you'd need to adjust quite some code. The initialization script has to go to a template so you can override it and you have to be able to pass your own transition functions.

**Comment by jankout** [comment]
> Yeah well, you'd need to adjust quite some code. The initialization script has to go to a template so you can override it and you have to be able to pass your own transition functions.

If I understand at the moment it isn't possible to add own behaviour to the conditional fields. I would like to influence it too - to add some nice animations.

**Comment by aschempp** [comment]
Feel free to provide a pull request 🙃

**Comment by aschempp** [comment]
Not sure if the latest version allows for this, but I'm closing it for now since it's very old.
