### ISSUE TITLE
JavaScript - defer Tag hinzufügbar?

### ISSUE THREAD

**Issue by mj1985** [terminal42/contao-conditionalformfields#29]
Moin moin,

da wir unser JS komplett vor dem schließenden Body-Tag ausgeben haben wir teilweise ein paar Timing-Probleme mit dem Laden von Inline-JS.
Spricht etwas dagegen in den Code hier:
https://github.com/terminal42/contao-conditionalformfields/blob/8ff9c0746e52182fd562a9eb63e87bf5e6931185/ConditionalFormFields.php#L212

ein `defer` hinzuzufügen?
Zum Hintergrund, wir lesen bereits `$GLOBALS['TL_JAVASCRIPT']` aus und fügen es ebenfalls vor dem `</body>` ein. Selbst wenn das Script im Head geladen wird, sollte es doch damit keine Probleme geben?

**Comment by aschempp** [comment]
Ich denke die Zeilen stammen noch aus Zeiten in denen es bei Contao kein `$GLOBALS['TL_BODY']` gab. Aus meiner Sicht sollten die Zeilen auch in's Template, dann könnte sie jeder so schreiben wie er will. Magst du dafür einen Pull Request machen?

**Comment by mj1985** [comment]
@aschempp Ich würde gerne helfen, bin aber damit etwas überfordert. Habe schon ein wenig rumprobiert es in `$GLOBALS['TL_BODY']` einzufügen, aber dann wurde die Anweisung nicht übergeben.

**Comment by aschempp** [comment]
Ich glaube wir können das nur ändern wenn wir das Widget komplett umbauen würden. Dann würde ich auch `<script type="application/json">` nutzen um die Daten auszugeben, und dann per globalem Script lesen.

Zur Zeit planen wir aber keinen Rewrite des Moduls. Wenn das für dich wichtig ist kannst du uns gerne eine E-Mail für eine Auftragsanfrage senden.
