### ISSUE TITLE
Support fieldset groups

### ISSUE THREAD

**Issue by aschempp** [terminal42/contao-conditionalformfields#3]
Supporting fieldsets might be difficult, but useful because they are part of Contao core. The javascript side would probably not be the big problem, but I'm not sure if fieldsets have a unique ID in the DOM.

However, we also need to validate or non-validate all fields inside that fieldset in the backend. Should be possible by acting on the START and STOP element.

**Comment by Toflar** [comment]
Meanwhile implemented.
