### ISSUE TITLE
muss Zwang-Paramter \Form $form sein?

### ISSUE THREAD

**Issue by srhinow** [terminal42/contao-conditionalformfields#30]
Hallo,
Ich habe für meine Erweiterung die Contao-Formklasse extendet. Da ich die Erweiterung "contao-conditionalformfields" einsetze, gibt er mir einen Fehler aus, dass  in der Datei "htdocs/vendor/terminal42/contao-conditionalformfields/ConditionalFormFields.php" Zeile 95 eine Instance der Klasse Form verlangt wird. Wenn ich die Zuweisung dort `\Form` und im Comment-Paramter raus nehme funktioniert es wie es soll.

Meine Frage:  Könntet ihr in eurem Modul an der beschrieben Stelle "\Form" raus nehmen, damit zukünitig auch vererbte Form-Klassen funktionieren? So würde dann auch meine Anpassung update sicher bleiben und andere die evtl ähnliches vorhaben, tappen nicht in dem selben Fehler.

Gruß Sven

**Comment by aschempp** [comment]
Wenn deine Erweiterung die Contao-Formklasse extended, dass musst deine Klasse das auch tun. Einfach `class MeineKlasse extends \Contao\Form`, damit sollte der Fehler auch verschwinden.

**Comment by srhinow** [comment]
genau das` class MeineKlasse extends \Contao\Form` macht meine Klasse auch und der Fehler ist in genau dieser Konstellation aufgetaucht.

**Comment by aschempp** [comment]
vielleicht müsstest du `extends \Form` machen?

**Comment by srhinow** [comment]
Ja das scheint es gewesen zusein. ;) 

Ich hatte es mit eigenem namespace und per 
`use Contao\Form;`
die Form-Klasse zugewiesen. 

Jetzt mach ich es wie du es vorgeschlagen hast per `extends \Form`
