### ISSUE TITLE
Error with MP_Forms

### ISSUE THREAD

**Issue by zonky2** [terminal42/contao-conditionalformfields#31]
```
Type error: Argument 4 passed to ConditionalFormFields::loadFormField() must be an instance of Form, instance of Contao\Form given, called in /kunden/123/webseiten/contao4_xyz.de/vendor/terminal42/contao-mp_forms/MPFormsFormManager.php on line 416
```

Workaround
https://github.com/terminal42/contao-conditionalformfields/blob/master/ConditionalFormFields.php#L95-L123
```diff
-    public function loadFormField($objWidget, $formId, $arrForm, \Form $form)
    {
+    public function loadFormField($objWidget, $formId, $arrForm, \Contao\Form $form)
    {
...
-    public function validateFormField($objWidget, $formId, $arrForm, \Form $form)
    {
+    public function validateFormField($objWidget, $formId, $arrForm, \Contao\Form $form)
    {
```

**Comment by Toflar** [comment]
In what contao version does that happen?

**Comment by zonky2** [comment]
sorry: Version 4.4.38

**Comment by richardhj** [comment]
Can you install `hotfix/2.2.3 as 2.2.3` of mp_forms and give feedback? Thank you.

**Comment by Toflar** [comment]
I guess I‘d rather fix the type hints :)

**Comment by richardhj** [comment]
I was thinking the type hint `\Form $form` is very usual for legacy code 🤔

**Comment by Toflar** [comment]
I wonder why this error happens anyway as Form should be aliased to \Contao\Form🤔

**Comment by richardhj** [comment]
Since Contao 4.5 or so. Before that, the autoloading is a mystery.

**Comment by aschempp** [comment]
It might be related to PHP 7.3, as that is more strict on these things afaik?
