### ISSUE TITLE
EventListener werden nicht hinzugefügt, wenn array_unique Elemente entfernt

### ISSUE THREAD

**Issue by sekmedia** [terminal42/contao-conditionalformfields#32]
Hallo,

zuerst vielen Dank für diese tolle Erweiterung!
Wir haben eventuell einen Bug gefunden. Unter bestimmten Bedingungen werden die change-Events von der initFields-Funktion nicht an die Inputs gebunden, wodurch keine Fieldsets mehr eingeblendet werden. Ich habe mit verschiedenen Bedingungen in Contao 3.5.38 getestet. Im Normalfall, wenn alles funktioniert, sieht der Parameter für den Aufruf der JS-Funktion conditionalFormFields so aus:
`{
        'fields': ["foo","bar"],
        'conditions': {"11151":"return (values.foo == 'ja');","11152":"return (values.bar == 'ja');"}
    }`

Wir haben nun einen Fall, bei dem fields nicht als Array, sondern als Object übergeben wird:
`{
        'fields': {"0":"foo","1":"bar","3":"baz"},
        'conditions': {"11151":"return (values.bar == 'ja');","11152":"return (values.foo == 'ja');","11157":"return (values.foo == 'nein' || values.baz == 'ja' || values.foo == 'ja');"}
    });
}`
Ich vermute, dass die Ursache das array_unique in ConditionalFormFields.php:250 ist. Doppelte Werte werden entfernt, json_encode macht schließlich aus dem Array das Object, womit die initFields-Funktion nicht mehr zurechtkommt.

In meinem Test hat es geholfen, in ConditionalFormFields.php:255 sicherzustellen, dass ein Array mit fortlaufenden numerischen Keys übergeben wird:
`return array_values($arrTriggerFields);`

**Comment by richardhj** [comment]
Great! The issue was fixed in 4eaaffa467cc7e52a766b9366f55ac94cd4b4346 // cc @Ukgcity
