### ISSUE TITLE
Form data from conditional fieldsets cannot be sent via Email

### ISSUE THREAD

**Issue by chberger** [terminal42/contao-conditionalformfields#33]
HI,

I've defined a form with multiple fieldsets. Each fieldset contains a checkbox menu. The first checkbox menu controls the visibility of the subsequent fieldsets. This is achieved by using your `contao-confitionalformfields` bundle and an appropriated `condition`.

![grafik](https://user-images.githubusercontent.com/3606282/64078706-2eb60e80-ccde-11e9-985e-e9e2453a5147.png)

This setup works nicely when you fill out the form in your browser. However, I have an issue while forwarding the selected data via email (data format raw). To be more precisely, some of the selected data just gets lost. This seems not be the case when I remove the conditions. So data from fieldsets wich are not controlled by conditions can be forwarded without any problems. Thus I'm afraid to raise this bug in contao/core.

I've also analysed the POST request data being sent. All the selected data seems to be transferred to the backend. 
![grafik](https://user-images.githubusercontent.com/3606282/64078804-a9cbf480-ccdf-11e9-8440-8eff1a3d6959.png)

However, only the data of the first control checkbox and the data of the first nested checkbox seems to be added to the email message:
```
Was trifft bei Ihnen zu?: 
Ich besitze bereits ein oder mehrere Führerscheinklassen, 
Ich beantrage die Klasse(n), 
Ich beantrage die Wiedererteilung der Klasse(n) 

Bereits im Besitz folgender Führerscheinklassen: B
```
Everything else got lost. I can reproduce this behaviour with `Contao 4.4.42` and `terminal42/contao-conditionalformfields 2.2.3`

Any help would be appreciated.

**Comment by chberger** [comment]
After some further investigation I've figured out, that the `validateFormField` method of 'ConditionalFormFields' sets some of my widgets to `disabled` although they are `enabled` in the frontend. 

`    public function validateFormField($objWidget, $formId, $arrForm, \Contao\Form $form)
    {
        // At this stage, widgets are already validated by the Form class
        // The mandatory (or any other restriction such as rgxp) settings are thus
        // already checked for fields that are conditional. We thus reset the
        // errors to none on them (ugly with reflection but there's no setter
        // on the Widget class so...)

        if (empty(static::$fieldsets[$form->id])) {

            return $objWidget;
        }

        $postData = $this->getFormPostData($arrForm['id']);
	
        foreach (static::$fieldsets[$form->id] as $fieldset) {
            foreach ($fieldset['fields'] as $fieldId) {
                if ($fieldId == $objWidget->id && !$fieldset['condition']($postData)) {

                    $reflection = new ReflectionClass($objWidget);
                    $errors = $reflection->getProperty('arrErrors');
                    $errors->setAccessible(true);
                    $errors->setValue($objWidget, []);
                    
                    // Widget needs to be set to disabled (#17)
                    $objWidget->disabled = true;
                }
            }
        }

        return $objWidget;`

I understand that this code should avoid sending hidden data from the previous session. However, in my case it blocks data which is actually expected at the backend. Once the `widget` is set to `disabled`, 
`\Widget::submitInput` will return` false`. And thus it won't be added to `$arrSubmitted` ([Form.php#L218](https://github.com/contao/core/blob/3.5.27/system/modules/core/forms/Form.php#L218)) and therefore also not processed in `processFormData`.

So the following condition evaluates to `true` for some of my `enabled` widgets:

`!$fieldset['condition']($postData)`

Related issues:
https://github.com/terminal42/contao-conditionalformfields/pull/17
https://github.com/terminal42/contao-conditionalformfields/pull/18

**Comment by aschempp** [comment]
Do I understand correctly that your form does not have a previous session (e.g. multi step form)?

**Comment by chberger** [comment]
Yes, I have a simple form without a previous session (e.g. multiple steps)
