### ISSUE TITLE
Feld-Werte werden nicht übermittelt

### ISSUE THREAD

**Issue by mapfei** [terminal42/contao-conditionalformfields#34]
Ich habe ein frisches Formular mit vier Select-Menüs angelegt. Das erste Select-Menü wird immer angezeigt - also ohne Fieldset/Bedingung. Select-Menü 2 und 3 sowie 4 umschließt jeweils ein Fieldset mit Bedingungen. Egal was ich auswähle: Per E-Mail (Rohdaten) werden immer nur die Werte aus dem ersten Select-Menü übermittelt. Die Werte aus den Fieldsets mit Bedingungen nicht. Das Verhalten bzw. die Anzeige der Select-Menüs im Frontend ist jedoch richtig. Entferne ich die Fieldsets, wird alles korrekt übermittelt. Auch die Speicherung in Leads erfolgt nicht.

Laut Chrome-Entwicklertools werden die Formulardaten jedoch übermittelt:

FORM_SUBMIT: auto_abo-test
REQUEST_TOKEN: F6bFpc8a38M1W7-5ihp_V5LazDtHav4LuZSOTi_6OEA
abo: abo2
praemie1: Prämie 1-1
praemie2: Prämie 2-2

Als Mail kommt jedoch nur folgendes an:

abo2
##form_praemie1##
##form_praemie2##

Siehe auch: https://community.contao.org/de/showthread.php?76877-CSV-Export-mit-Notification-Center-bleibt-leer

Es scheint als werden nur die Felder nicht übermittelt, welche von einem Fieldset umschlossen werden, welches mehrere (AND) Bedingungen abfragt.

**Comment by richardhj** [comment]
Chances are the issue got fixed in version 2.3.3.
