### ISSUE TITLE
Feld in Condition wird im NC als Token angezeigt

### ISSUE THREAD

**Issue by zonky2** [terminal42/contao-conditionalformfields#35]
ich habe ein Select-Menü und ein CFF Text (Sonstiges), welches sichtbar sein soll, wenn eine bestimmte Checkbox gesetzt ist - Anzeige funktioniert...

Problem ist im NC.

* wenn Textfeld Sonstiges sichtbar, wird in der NC-Mail auch der Text ausgegeben
* wenn Textfeld Sonstiges nicht sichtbar, wird in der NC-Mail der Token `##form_sonstiges## ` ausgegeben

aktueller Workaround mit `{if form_sonstiges!=''}##form_sonstiges##{endif}`

Im Gegensatz zu #34 werden die Werte in Leads korrekt gespeichert

**Comment by aschempp** [comment]
wie steuerst du die Sichtbarkeit? nur weil das Feld in deinem CSS ausgeblendet wird, wird es ja trotzdem an den Webserver gesendet.

**Comment by zonky2** [comment]
Gesteuert über `in_array('Sonstiges', $zustaendig)` als Bedingung
getestet im Chrome

POST-Parameter
Feld nicht sichtbar:
```
zustaendig: 
zustaendig[]: Geschäftsführung
erste_teilnahme: nein
```

Feld sichtbar:
```
zustaendig: 
zustaendig[]: Sonstiges
sonstiges: SONSTIGES-Test
erste_teilnahme: nein
```

**Comment by aschempp** [comment]
Das Verhalten ist richtig. Wenn das Feld nicht da ist (weil ausgeblendet), dann ist das Token nicht vorhanden. Simple Tokens werden nur ersetzt wenn sie exakt vorhanden sind. Du musst also die If-Bedingung machen.
