### ISSUE TITLE
Mehere Formularfelder mit gleichem Feldnamen verwerden

### ISSUE THREAD

**Issue by BennyK80** [terminal42/contao-conditionalformfields#38]
Wenn eine Bedingung erfüllt ist, soll ein entsprechendes Select-Menü mit anderen Werten aber gleichem Feldname verwendet werden. 

Da Feldnamen eindeutig sein müssen, stellt sich mir die Frage, wie das mit dieser Erweitung machbar sein könnte.

Gibt es dafür eine Lösung?

**Comment by Toflar** [comment]
Nein :)

**Comment by BennyK80** [comment]
Danke für die Info!
