### ISSUE TITLE
Compatibility to mp_forms

### ISSUE THREAD

**Issue by zonky2** [terminal42/contao-conditionalformfields#40]
Compatibility to mp_forms
see https://github.com/terminal42/contao-mp_forms/issues/40

maybe, if mp_forms is present, the values from previous steps should be present in the javascript and should be available alternatively to query the input fields.

**Comment by Toflar** [comment]
Closing in favor of the PR https://github.com/terminal42/contao-conditionalformfields/issues/40.

**Comment by zonky2** [comment]
PR #42 ...
