### ISSUE TITLE
Support for mandatory fields

### ISSUE THREAD

**Issue by zonky2** [terminal42/contao-conditionalformfields#41]
Support for mandatory fields

If mandatory fields are hidden by a condition, the form cannot be submitted or, in the case of mp_forms, no next step can be taken

**Comment by zonky2** [comment]
As far as I see it, the problem is the validation of the mandatory fields by Contao.
The conditions are made purely by JavaScript and hide the fieldset (display: none) and set the widgets to disabled - this does not result in HTML5 validation.

An interesting question might be how to tell Contao that certain fields are hidden and should not be validated...

**Comment by aschempp** [comment]
that should already be the case through https://github.com/terminal42/contao-conditionalformfields/blob/main/ConditionalFormFields.php#L128 🤔

**Comment by theDyingMountain** [comment]
There is also a problem with nested conditions. In the subchilds the widgets are not set disabled...

**Comment by ff1601com** [comment]
@aschempp I have the same problem as zonky2 when it comes to hidden mandatory fields. Whether they are in nested conditions or not does not make a difference.

The hidden mandatory fields are getting set to ```disabled="disabled"``` and are hidden if the condition is not met.
But when a user tries to submit the form they throw errors and the form can't be submit.

Is there a workaround I am missing or something special to configurate for hidden mandatory fields?
Installed version is the latest version of the package.

**Comment by zonky2** [comment]
Für Umbau werfe ich mal 150€ in den Hut

**Comment by aschempp** [comment]
Should be fixed in release 3.0.0. @zonky2 feel free to sponsor directly on GitHub 😉 
https://github.com/sponsors/terminal42

**Comment by zonky2** [comment]
Github-Sponsoring ist (ab-)rechnungstechnisch Grütze...
