### ISSUE TITLE
No functionality in 2.3.0 anymore?

### ISSUE THREAD

**Issue by danielkochc** [terminal42/contao-conditionalformfields#43]
I updated to the latest version 2.3.0 via Contao Manager. After that, the conditional form field shows no functionality at all. No (JS) Errors, nothing. There were no changes made at the form configuration. 

What I tried:
- clear caches manually
- change form fields to other values and names (of course matching the dependencies of trigger and target)
- tested on Firefox and Chrome

After reverting back to my previous version 2.2.3 the functionality was restored.

Version 2.2.4, I found while writing this, works also as expected.

**Comment by Toflar** [comment]
The current release is 2.3.1, does this fix your issues?

**Comment by danielkochc** [comment]
It works now in the test system, thank you.

I don't know why my update this morning got version 2.3.0, instead of the the latest version available since 5 days (as I seen by now). Nevermind. Thank you for the fast response.

I guess this can be closed.
