### ISSUE TITLE
größer kleiner operatoren

### ISSUE THREAD

**Issue by kehr-solutions** [terminal42/contao-conditionalformfields#47]
Ich habe folgendes Problem. Ich würde gerne ein Feld auf größer bzw. kleiner abfragen.

Wenn ich $feld_1 > 5 eintrage funktioniert es ohne Probleme.

Wenn ich aber $feld_1 < 5 eintrage erhalte in in der Console eine Fehlermeldung: `Uncaught SyntaxError: Unexpected token ';'`
Hier wird das kleiner-Zeichen umgewandelt `values.feld_1 &lt; 5`

**Comment by aschempp** [comment]
Fixed in 6749cab50682fee16c3d5a81aba2f08dd0cb4cd0
