### ISSUE TITLE
Data of previous steps get lost with contao-mp_forms and contao-ajaxform

### ISSUE THREAD

**Issue by markus361** [terminal42/contao-conditionalformfields#48]
Contao: 4.4.46
contao-conditionalformfields: 2.3.3
contao-mp_forms: 4.1.0
contao-ajaxform: 1.1.1

In my example:
On step 2 there are 2 radios
On step 3 there is a fieldset with ConditionalFormField activated, which checks those radios

Now when on step 3 there is no data from step 2 available and the condition is not working on the fieldset.

In the conditionalformfields.js file on line 117 I added
`console.log($this.fields);`
the object is empty when on step 3

EDIT
contao-ajaxform not necessarily required

**Comment by aschempp** [comment]
Version 3 is a complete rewrite. Since I don't use the combination of extension, feel free to provide a pull request that fixes the issue for you 🙃
