### ISSUE TITLE
Error undefined 'array key' with debug mode and php 8.0

### ISSUE THREAD

**Issue by Enrica-r** [terminal42/contao-conditionalformfields#52]
The debug mode (developer mode) throws an exeption on line 211 in class ConditionalFormFields because array key does not exist. See error in Symfony debug console
![error-message](https://user-images.githubusercontent.com/2463365/141094537-afb3b559-9a36-494e-a786-c365fb649df3.PNG)
:

Thank you for your correction.

**Comment by mlwebworker** [comment]
Ich kann das Problem bestätigen PHP 8.0.13 und Contao 4.12.5
Hie der komplette Stack Trace

`ErrorException:
Warning: Undefined array key "CONDITIONALFORMFIELDS"

  at vendor/terminal42/contao-conditionalformfields/ConditionalFormFields.php:211
  at ConditionalFormFields->outputFrontendTemplate()
     (vendor/contao/core-bundle/src/Resources/contao/classes/FrontendTemplate.php:138)
  at Contao\FrontendTemplate->compile()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Template.php:327)
  at Contao\Template->getResponse()
     (vendor/contao/core-bundle/src/Resources/contao/classes/FrontendTemplate.php:87)
  at Contao\FrontendTemplate->getResponse()
     (vendor/contao/core-bundle/src/Resources/contao/pages/PageRegular.php:60)
  at Contao\PageRegular->getResponse()
     (vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendIndex.php:339)
  at Contao\FrontendIndex->renderPage()
     (vendor/symfony/http-kernel/HttpKernel.php:158)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:80)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (web/preview.php:33) `

**Comment by aschempp** [comment]
Fixed in version 2.3.4
