### ISSUE TITLE
verschachtelte Bedingungen funktionieren leider nicht korrekt

### ISSUE THREAD

**Issue by frontendschlampe** [terminal42/contao-conditionalformfields#54]
dev-develop und Contao 4.9.29

Ich habe eine Checkbox, die bei Aktivierung weitere Felder anzeigen soll mit folgender Bedingung:
`(verbindliche_buchung == 'verbindliche_buchung_bestaetigt')`
Das funktioniert.

Innerhalb der freigegebenen Felder habe ich ein Radio-Button-Menü (`notfallkontakt`) mit vier Optionen (`nur-mobil`, `nur-email`, `mobil-email`, `kein-kontakt`). Je nach Auswahl einer Option sollen weitere Felder angezeigt werden:

1. `(notfallkontakt == 'nur-mobil') || (notfallkontakt == 'mobil-email')`
2. `(notfallkontakt == 'nur-email') || (notfallkontakt == 'mobil-email')`

Es wird das Feld für 1. immer angezeigt. Das 2. funktioniert. Wenn ich die Reihenfolge tausche, funktioniert das andere Feld - also es funktioniert immer das erste Fieldset. In der Konsole kommt folgende Meldung: 

```
[Error] TypeError: null is not an object (evaluating 'form.elements')
	(anonyme Funktion) (conditionalformfields.js:18)
	forEach
	init (conditionalformfields.js:7)
	(anonyme Funktion) (conditionalformfields.js:103)
	forEach
	(anonyme Funktion) (conditionalformfields.js:101)
```

Mit der Version 2.3.4 gibt es da keinerlei Probleme.

**Comment by aschempp** [comment]
Kannst du bitte prüfen ob die neuste Version (neuster dev-develop) das Problem behebt?
