### ISSUE TITLE
php warning at cache-warmup

### ISSUE THREAD

**Issue by asaage** [terminal42/contao-conditionalformfields#55]
Is there something wrong with the dca?
I noticed this here after installing conditionalformfields (contao4.13 / php8.0):
```
 // Warming up the cache for the prod environment with debug                    
 // false                                                                       

PHP Warning:  Undefined array key "fieldsetfsStart" in /var/www/contao/var/cache/prod/contao/dca/tl_form_field.php on line 326
 [OK] Cache for the "prod" environment (debug=false) was successfully warmed.
```

**Comment by aschempp** [comment]
Are you on the latest version 3.0?

**Comment by asaage** [comment]
actually 2.3.4
when i installed it first (under contao 4.4 or 4.9) the manager locked it at ^2.3.
The warning is gone in 3.0.
I wonder why the manager does not suggest updates of major versions.

**Comment by aschempp** [comment]
You might want to read up on https://getcomposer.org/doc/articles/versions.md 😊

**Comment by asaage** [comment]
That does not tell me how i am supposed to know that there i a new release and the ^2.3 was decided for me earlyer 😉
