### ISSUE TITLE
Nach Update auf 3.0.0 keine Funktion

### ISSUE THREAD

**Issue by Schmidty2** [terminal42/contao-conditionalformfields#56]
Hallo,
nach dem Update auf 3.0.0 wird das Fieldset im Frontend beim Aufruf des Formulars nicht mehr ausgeblendet.
Wenn man zurückgeht auf die Version 2.3.4 funktioniert wieder alles wie gewünscht.
Contao 4.13.4
PHP 7.4.29
Provider All-Inkl
Conditionalformfields 3.0.0
In der Konsole ist eine Fehlermeldung sichtbar, meine Feldkofiguration, die fehlerhafte Frontendausgabe und die Konseolenmeldung sind hier zu sehen:

![Frontend](https://user-images.githubusercontent.com/2067428/170697788-07fc5f62-aed1-4d7c-a27b-c5c35623e3ef.jpg)

![Backend-Konfiguration-1](https://user-images.githubusercontent.com/2067428/170697791-3ac7773e-8514-43cf-8eca-92a19e629b35.jpg)

![Backend-Konfiguration-2](https://user-images.githubusercontent.com/2067428/170697793-f7f6aee7-8dcb-431f-bf8f-fcaddbe4bd30.jpg)

![Fehlermeldung-Konsole](https://user-images.githubusercontent.com/2067428/170697806-15d53392-c3fc-424b-8189-abbc736be74b.JPG)

**Comment by baumannsven** [comment]
@Schmidty2 

Da dieser Fehler im Frontend besteht. Wäre für die Entwickler eventuell wichtig zu wissen, was du für einem Browser und welches Betriebssystem du nutzt mit Angabe der Version.

**Comment by Schmidty2** [comment]
Hallo,
der Fehler tritt unter Windows 10 Pro x64 mit dem Firefox 100.0.2 auf.
Aber auch mit Chrome 102.0.5005.63 (gleiches Windows) tritt der Fehler auf.
Auf dem iPhone 12 mit Safari (iOS 15.5) ist der Fehler ebenfalls vorhanden.

Die notwendigen Zugangsdaten und ein Link zur Seite kann ich gerne per PN zukommen lassen.

**Comment by aschempp** [comment]
Hast du noch andere Felder im Formular die ev. zu einem Konflikt führen? Versuch mal alle anderen Felder zu entfernen/deaktivieren um das auszuschliessen.

**Comment by Schmidty2** [comment]
Hallo,
ich habe in einer Kopie des Formulars mal alles gelöscht bis auf die notwendigen Felder.
Testen konnte ich nur auf einem iPad mit iOS 15.5 und Safari, da tritt das Problem mit dem Testformular immer noch auf.
Hier der Formularaufbau (die Konfiguration wie oben unverändert):

![52A63D4D-7CDB-418B-A3C6-78CD76E2B2F7](https://user-images.githubusercontent.com/2067428/170894434-7af1d73a-0237-4ed6-9fe1-73e313c289bc.jpeg)

Und die Frontend-Ausgabe:

![FE809C83-7E83-42A5-81E1-6066C0CF3F86](https://user-images.githubusercontent.com/2067428/170894595-641d4c66-6d9f-4c29-bf4c-384e34ed7614.jpeg)

**Comment by aschempp** [comment]
I can see the problem is most likely the dash in the second field name (`programm-nachtflug`).

**Comment by aschempp** [comment]
I have added a simple field validation in cb34e319865c90b1c34de030f9f28de249bd0c46. In your case that should continue to work since you don't use the `programm-nachtflug` field.
