### ISSUE TITLE
Elemente außerhalb des Fieldset werden mit ausgeblendet

### ISSUE THREAD

**Issue by do-while** [terminal42/contao-conditionalformfields#59]
Hallo,
mein Formular ist wie folgt aufgebaut:
- Checkbox 1
- Checkbox als schalter
- [ Fieldset Anfang (Bedingung schalter == '1')
- [ Erklärungsfeld
- [ Fieldset Ende
- Absendefeld
Die Checkbox (Schalter) aktiviert/deaktiviert die Anzeige des Erklärungsfelds - soweit OK

Wenn jetzt aber die Checkbox 1 auch eine Bedingung bekommt (hatte hier zuvor auch ein Fieldset-Feld, habe dann auf Checkbox umgestellt), dann wird auch hier die Bedingung überwacht, obwohl es außerhalb des Fieldsets liegt. 
Die Bedingung ist auch nicht einsehbar, jedoch im Hintergrund in der Datenbank gespeichert. Eigentlich dürfte dieses Feld nicht die Bedingung auswerten.
Offenbar ist der Fehler nur bei Checkboxen, andere Felder scheint es nicht zu betreffen.

**Comment by do-while** [comment]
Ach so:
PHP 8.1.3
Contao 4.13.5
terminal42/contao-conditionalformfields: Version 3.0.5

**Comment by aschempp** [comment]
should be fixed in 138c58b999f619aace833f76fcffab8f86dd6794
