### ISSUE TITLE
javascript error: SyntaxError: identifier starts immediately after numeric literal

### ISSUE THREAD

**Issue by xantippe** [terminal42/contao-conditionalformfields#6]
Hallo,

ich habe ein Checkboxmenü mit 
Feldname: 1_fb
Optionswerte: 1_fb_1, 1_fb_2, 1_fb_3 .... 1_fb_5

Wenn die erste Checkbox angeklickt wird, soll ein weiteres Checkboxmenü eingeblendet werden - das ist in einem Fieldset mit der Option ```in_array('1_fb_1', $1_fb)```

Im FE kommt die Meldung auf der JS-Konsole
```SyntaxError: identifier starts immediately after numeric literal
ystack) != -1) : false; }; return (in_array('1_fb_1', values.1_fb));
```

**Comment by Toflar** [comment]
In JavaScript dürfen Werte nie mit einem numerischen Wert beginnen. Du darfst insofern deine Optionen auch nicht mit Zahlen beginnen. Das ist generell eine schlechte Idee :-) Das ist wie Leerzeichen in Dateinamen - meistens funktioniert's aber machen sollte man es trotzdem nicht :-D

**Comment by xantippe** [comment]
Dann könnte das aks kleiner Hinweis in die Beschreibung...
