### ISSUE TITLE
Im Edge und Chrome funktioniert die Ansicht nicht. Es wird dort alles angezeigt

### ISSUE THREAD

**Issue by m-werk** [terminal42/contao-conditionalformfields#67]
Hallo, ich habe auch ein Problem mit den Browsern Chrome und Edge. Im Firefox funktioniert die Anzeige wunderbar, nur in den anderen Browsern werden untereinander alle anderen Formulare auch angezeigt. 

Gibt's dafür vielleicht eine Lösung? Leider kann ich jetzt keine Seite als Beispiel nennen, da es in einem geschlossenen Bereich ist. Aber ich kann einen Zugang per PN zukommen lassen. Nur muss ich den dann wieder löschen.

Bei diesem Bild ist es falsch, hier werden alle andere Formulare auch angezeigt.
![2022-11-02_09h04_05](https://user-images.githubusercontent.com/1488276/199433823-52d8563f-3eb5-42e4-9bf1-76eb4e06b392.jpg)

Und so soll es aussehen. Hier im Firefox funktioniert alles.
![2022-11-02_09h04_36](https://user-images.githubusercontent.com/1488276/199433880-9438c17f-9300-4b34-accc-957e20fe53c0.jpg)

LG, Andi

**Comment by Toflar** [comment]
Does 3.0.7 fix the issue?

**Comment by m-werk** [comment]
Ja, mit der neuen Version funktioniert es. Ich habe es via Contao Manager installiert, obwohl dort NICHT angezeigt wurde, dass es eine neu version gibt. Jetzt sieht es so aus: 
![grafik](https://user-images.githubusercontent.com/1488276/201864278-f51a6ea9-13f9-427b-8db5-7be922cce1a6.png)

**Comment by Toflar** [comment]
Das wäre dann ein Manager-Issue.
