### ISSUE TITLE
FR: "native" Unterstützung der Formularfelder

### ISSUE THREAD

**Issue by xantippe** [terminal42/contao-conditionalformfields#7]
Hallo,

schön wäre die "native" Unterstützung der Formularfelder - also ohne zus. Fieldset als "Klammer/Umschlag-Element".

Dank!

**Comment by Toflar** [comment]
Das war so in Version 1 und funktioniert so nicht, deswegen haben wir's umgebaut. Viele Felder (z.B. eigenes HTML) haben kein umgebendes Element und können deshalb nicht automatisiert vom JS angesprochen und ein- oder ausgeblendet werden.

**Comment by xantippe** [comment]
hmmm... o.k. - wenn auch schade :-(
