### ISSUE TITLE
"data-cff-condition fieldsets" are not initialized if the form contains a script tag

### ISSUE THREAD

**Issue by theDyingMountain** [terminal42/contao-conditionalformfields#76]
If the form includes a script all field sets are not initialized, and no event listeners are registered, even if the script tag is empty.

**Comment by aschempp** [comment]
Ich kann das Problem nicht reproduzieren. Bitte stell sicher dass du keine anderen Javascript-Fehler auf der Seite hast. Ansonsten bitte posten wenn was in der Dev-Konsole steht.
