### ISSUE TITLE
Loading data and nothing happens

### ISSUE THREAD

**Issue by xApep** [terminal42/contao-conditionalformfields#78]
When clicking "only show..." the data is just loading and nothing happens

![image](https://user-images.githubusercontent.com/1315340/233263206-5bb3d8ea-73f1-4b6a-b7a3-d5ebaba98560.png)

Version 3.0.11
Contao 4.13.19

**Comment by fritzmg** [comment]
Did you update your database?

**Comment by Toflar** [comment]
I also think this is related to something else. If you install the extension in an empty Contao setup, do you still get this issue? (highly unlikely - everybody would have this issue)
