### ISSUE TITLE
Bug: Pflichtfeld-Sternchen fehlt bei Einblendung nach negativer Prüfung 

### ISSUE THREAD

**Issue by xantippe** [terminal42/contao-conditionalformfields#8]
Hallo,

folgender Aufbau:
* 1. Ebene: Checkbox-Menü als Pflichtfeld
* 2. Ebene: weitere Pflichtfelder
* 2  Ebene wird eingeblendet, wenn Checkbox 1 geklickt

* ruft man das Formular auf und klickt auf Checkbox 1, ist das Pflichtfeldsternchen zu sehen
* ruft man das Formular auf und klickt auf Checkbox, kommt Fehlermeldung wg. Pflichtfeld => wird nun Checkbox 1 angeklickt, ist in Ebene 2 kein "Sternchen" für die Pflichtfelder zu sehen (wird aber geprüft)

... besser zu sehen anhand der Screenshots:

![zwischenablage14](https://cloud.githubusercontent.com/assets/1045318/8227704/ba385b48-15a9-11e5-9182-552ee035dce3.jpg)

![zwischenablage15](https://cloud.githubusercontent.com/assets/1045318/8227709/c021d32c-15a9-11e5-94c9-58a4a7a48a80.jpg)

![zwischenablage16](https://cloud.githubusercontent.com/assets/1045318/8227713/c5a21410-15a9-11e5-9c81-be53b8a91420.jpg)

**Comment by xantippe** [comment]
Ich glaube, dass Problem ist Contao, welches die Pflichtfeldsternchen entfernt...

als ersten Workaround:

```
        showFieldset: function(id) {
            this.fieldsets[id].show();
            
            this.fieldsets[id].children('fieldset.mandatory').each(function() {
          	  	if($(this).children('legend').children('span.mandatory').length < 1) {
          	  		$(this).children('legend').append('<span class="mandatory">*</span>');
          	  	}    
            });

            $(this.fieldsetFields[id]).each(function() {
            		var label = $("label[for='"+$(this).attr("id")+"']");
            	  if(label.hasClass('mandatory')) {
            	  	if(label.children('span.mandatory').length < 1) {
            	  		label.append('<span class="mandatory">*</span>');
            	  	}
            	  }
                $(this).attr('disabled', false);         
            });
        },
```

**Comment by aschempp** [comment]
Fixed in 90b30bb905c57ada2c2b9da75aa6f28a561df532
