### ISSUE TITLE
Warning: Undefined array key "fieldsetfsStart"

### ISSUE THREAD

**Issue by falkgeist** [terminal42/contao-conditionalformfields#86]
Version: 2.3.4
Ich denke mal, ihr wisst, was da zu tun wäre, wenn mal jemand dazu kommt. :)
https://github.com/terminal42/contao-conditionalformfields/blob/46d98f2beac86140dc5b10a21a990215f57f56f0/dca/tl_form_field.php#L24C1-L24C211

**Comment by fritzmg** [comment]
You need to update to v3.

**Comment by falkgeist** [comment]
Ah, sorry, I stupidly assumed, that I couldn't use v3, but actually it was high time ^^
resolved, thanks!
