### ISSUE TITLE
Checkboxen werden nicht unterstützt

### ISSUE THREAD

**Issue by FrischBlau** [terminal42/contao-conditionalformfields#91]
Hi,

Checkboxen werden in Version 3.11 nicht unterstützt (siehe auch https://github.com/terminal42/contao-conditionalformfields/issues/2#issuecomment-1834066056) In älteren Versionen ging das.
Contao macht bei den Checkboxen aus dem Feldnamen "foo" -> 'name="foo[]"'
Eine condition wie "foo == 'bar'" greift damit nicht und "foo[] == 'bar'" ist als Eingabe nicht möglich. 

- Contao 4.13
- PHP 8.2
- contao-conditionalformfields Version 3.11

Schönen Nachmittag

**Comment by fritzmg** [comment]
Both `foo == 'bar'` and `foo[] == 'bar` would be wrong. `foo` is the correct variable name, but since in your case it is a checkbox with multiple options, it is an array of values, not single array.

You need to use

```
in_array('bar', foo)
```
