### ISSUE TITLE
Does it work with Contao 5.3 ?

### ISSUE THREAD

**Issue by amenk** [terminal42/contao-conditionalformfields#93]
Does the module work with Contao 5.3? 
If not, what needs to be fixed?

We will test and eventually update the readme, if it works.

**Comment by fritzmg** [comment]
This extension is unlocked for Contao 5. You will need to test and see for yourself if there happen to be any issues.

**Comment by phpinsomniac** [comment]
Seems to work properly with 5.3 so far. If we come across any problems we will give an update here @fritzmg

**Comment by cscheibelhut** [comment]
Seems to work properly with 5.3 so far. If we come across any problems we will give an update here @fritzmg
